insert into keylocations
values
("KL-1","NH-12T","NUST Medical  Centre","Hospital","Hospital","GYM, Prayer Area, Mess, Laundry, Badminton court, Table Tennis, Vending Machine, Electric Oven and Iron, Internet facility, Radiator Heating System, TV Room","C:\\Users\\hp\\Documents\\Images\\NUST Medical Centre.jpeg"),
("KL-2","NH-12T","NUST Central Library","Library","NUST main Library","Maximum Books available, Prayer Area, Toilets, Alumni Corner, Parking","C:\\Users\\hp\\Documents\\Images\\NUST Central Library.jpeg"),
("KL-3","NH-12T","NUST Main  Office","Office","NUST HQ, HR branch, Exam branch","NUST HQ, HR branch, Exam branch","C:\\Users\\hp\\Documents\\Images\\NUST Main Office.jpeg"),
("KL-4","NH-12T","NUST Exam Branch","Office","NUST main exam office","NUST main exam office","C:\\Users\\hp\\Documents\\Images\\NUST Exam Branch.jpeg"),
("KL-5","NH-12T","NUST HR Branch","Office","NUST main HR office","NUST main HR office","C:\\Users\\hp\\Documents\\Images\\NUST HR Branch.jpeg"),
("KL-6","NH-12T","CIPS","Office","Office of International peace","Jinnah Faculty Mess, Jinnah Auditorium","C:\\Users\\hp\\Documents\\Images\\CIPS.jpeg"),
("KL-7","NH-12T","Jinnah Auditorium","Auditorium","place to held interaction of students with National, International and Celebrity guests","place to held interaction of students with National, International and Celebrity guests","C:\\Users\\hp\\Documents\\Images\\Jinnah Auditorium.jpeg"),
("KL-8","NH-12T","NSTP","Offices","NSTP","Different offices, Askari Bank, Parking, Cafe, Restaurant","C:\\Users\\hp\\Documents\\Images\\NSTP.jpeg"),
("KL-9","NH-12T","C1 Tuck Shop","Mart","Grocery mart","Grocery mart","C:\\Users\\hp\\Documents\\Images\\C1 Tuck Shop.jpeg"),
("KL-10","NH-12T","C2 Tuck Shop","Mart","Grocery mart","Grocery mart","C:\\Users\\hp\\Documents\\Images\\C2 Tuck Shop.jpeg"),
("KL-11","NH-12T","C2 Gift Shop","Shop","Gift shop","Gift shop","C:\\Users\\hp\\Documents\\Images\\C2 Gift Shop.jpeg"),
("KL-12","NH-12T","C2 Barber Shop","Salon","Hair Cut, Shave etc.","Hair Cut, Shave etc.","C:\\Users\\hp\\Documents\\Images\\C2 Barber Shop.jpeg"),
("KL-13","NH-12T","C2 Tailor Shop","Shop","Clothes sewing, Iron","Clothes sewing, Iron","C:\\Users\\hp\\Documents\\Images\\C2 Tailor Shop.jpeg"),
("KL-14","NH-12T","C2 Stationary Shop","Shop","Stationary, Photocopies","Stationary, Photocopies","C:\\Users\\hp\\Documents\\Images\\C2 Stationary Shop.jpeg"),
("KL-15","NH-12T","C2 Photo Shop","Photo Shop","Photography","Photography","C:\\Users\\hp\\Documents\\Images\\C2 Photo Shop.jpeg"),
("KL-16","NH-12T","Stationary Hub","Shop","Stationary, Photocopies","Stationary, Photocopies","C:\\Users\\hp\\Documents\\Images\\Stationary Hub.jpeg"),
("KL-17","NH-12T","NUST Exam Hall","Hall","FirstAid medicare, Water, Tiolets","FirstAid medicare, Water, Tiolets","C:\\Users\\hp\\Documents\\Images\\NUST Exam Hall.jpeg"),
("KL-18","NH-12T","Admin Branch","Office","HBL Bank, Alumni Office, Pakistan Post, Admin Block","HBL Bank, Alumni Office, Pakistan Post, Admin Block","C:\\Users\\hp\\Documents\\Images\\Admin Branch.jpeg");
