insert into recreational_spots values 
("RS-1","NH-12T","Old GYM","Fitness Place","GYM, Badminton Court, Snooker Club","D:\\2nd semester\\Images\\Oldgym.jpeg", 4.2),
("RS-2","NH-12T","Sports Complex","Fitness Place","GYM, Badminton Court, Snooker Club, Bowling Alley","D:\\2nd semester\\Images\\CentralGYM.jpeg", 4.6),
("RS-3","NH-12T","Saddle Club","Horse riding Place","offers Saddle, Outfits etc.","D:\\2nd semester\\Images\\SaddleClub.jpeg", 4.4),
("RS-4","NH-12T","Swimming Pool","Swimming Place","offers swimming goggles, Swimsuits etc.","D:\\2nd semester\\Images\\SwimmingPool.jpeg", 4.1),
("RS-5","NH-12T","Athletics Ground","Ground","can play different activities","D:\\2nd semester\\Images\\AthleticsGround.jpeg", 4.3),
("RS-6","NH-12T","Rock Climbing Wall","Fun activity place","fully safety measures","D:\\2nd semester\\Images\\RockClimbingWall.jpeg", 4.5),
("RS-7","NH-12T","Basketball Court","Sports ground","Sports ground","D:\\2nd semester\\Images\\BasketballCourt.jpeg", 4.0),
("RS-8","NH-12T","Tennis Court","Sports ground","Sports ground","D:\\2nd semester\\Images\\TennisCourt.jpeg", 4.4),
("RS-9","NH-12T","Children Park","Park","Park","D:\\2nd semester\\Images\\ChildrenPark.jpeg", 4.6),
("RS-10","NH-12T","Piston Cup Track","Cars exhibition ground","Cars, Sports cars exhibition Area","D:\\2nd semester\\Images\\PistonCupTrack.jpeg", 4.3),
("RS-11","NH-12T","NUST Lake","Tranquil Place","Lake, Sitting Area, Foodspots etc.","D:\\2nd semester\\Images\\NUSTLake.jpeg", 4.8),
("RS-12","NH-12T","Volleyball Court","Sports ground","Sports ground","D:\\2nd semester\\Images\\VolleyballCourt.jpeg", 4.2),
("RS-13","NH-12T","NBS Ground","School ground","School ground","D:\\2nd semester\\Images\\NBSGround.jpeg", 4.1),
("RS-14","NH-12T","NUST Trail","Hiking trail","Hiking trail","D:\\2nd semester\\Images\\NUSTTrail.jpeg", 4.7),
("RS-15","NH-12T","Machoor Garden","Park","Park","D:\\2nd semester\\Images\\MachoorGarden.jpeg", 4.5),
("RS-16","NH-12T","Helipad Ground","Ground","Ground","D:\\2nd semester\\Images\\HelipadGround.jpeg", 4.2),
("RS-17","NH-12T","C1-Basketball Court","Sports ground","Sports ground","D:\\2nd semester\\Images\\C1BasketballCourt.jpeg", 4.3),
("RS-18","NH-12T","HBL Football Ground","Sports ground","Sports ground","D:\\2nd semester\\Images\\HBLFootballGround.jpeg", 4.4),
("RS-19","NH-12T","HBL Volleyball Court","Sports ground","Sports ground","D:\\2nd semester\\Images\\HBLVolleyballCourt.jpeg", 4.6),
("RS-20","NH-12T","HBL Futsal Ground","Sports ground","Sports ground","D:\\2nd semester\\Images\\HBLFutsalGround.jpeg", 4.5),
("RS-21","NH-12T","HBL Cricket Ground","Sports ground","Sports ground","D:\\2nd semester\\Images\\HBLCricketGround.jpeg", 4.1),
("RS-22","NH-12T","SNS Ground","School ground","School ground","D:\\2nd semester\\Images\\SNSGround.jpeg", 4.2),
("RS-23","NH-12T","NICE Ground","School ground","School ground","D:\\2nd semester\\Images\\NICEGround.jpeg", 4.0),
("RS-24","NH-12T","Squash Court","Sports club","Proper Area for squash","D:\\2nd semester\\SquashCourt.jpeg", 3.7),
("RS-25","NH-12T","SCME Ground","Sports and events helding area","School ground","D:\\2nd semester\\SCMEGround.jpeg", 4.7);